# Generated by Django 4.0 on 2021-12-19 06:20

import Accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.IntegerField()),
                ('expiry', models.DateTimeField(default=Accounts.models.OTP.expiry)),
                ('otp_account_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Accounts.useraccount')),
            ],
        ),
    ]
