# Generated by Django 4.0 on 2021-12-19 06:25

import Accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_alter_otp_expiry_alter_otp_otp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=Accounts.models.OTP.expiry),
        ),
    ]
